site_name: CEMIG SAÚDE
site_description: >-
    Documentação simplificada, auxiliando no seu dia-a-dia. Pesquise ou navegue nos botões abaixo.

theme: 
  name: material
  custom_dir: !ENV [THEME_DIR, "material"]

  include_search_page: false
  search_index_only: true

  static_templates:
    - 404.html
  
  language: pt
  features:
    - content.code.annotate
    # - content.tabs.link
    - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.sections
    - navigation.tabs
    #- navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - navigation.expand
    #- toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: white
      accent: white
      toggle:
        icon: material/toggle-switch
        name: Modo Escuro
    - scheme: slate
      primary: white
      accent: white
      toggle:
        icon: material/toggle-switch-off-outline
        name: Modo Claro
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/database-eye


plugins:
  - search
  - table-reader:
      data_path: "docs/assets/tables"

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


repo_name: CEMIG SAÚDE
repo_url: https://www.cemigsaude.org.br/site/home
edit_uri: ""

nav:
    - Home: index.md
    - Ciência de Dados: 
      - src/ciencia_de_dados/index.md
      - Sobre: src/ciencia_de_dados/index.md
      - Análise do código: src/ciencia_de_dados/index.md
      - Dicionario de Dados: src/ciencia_de_dados/index.md
      - Ajuda: 
        - src/ciencia_de_dados/ajuda/index.md
        - src/ciencia_de_dados/ajuda/index.md
    - Engenharia: 
      - src/engenharia/index.md
      - Sobre: src/engenharia/getting_started.md
      - Análise do código: src/engenharia/code.md
      - Dicionario de Dados: src/engenharia/arquitetura/dicionario_de_dados.md
      - Arquitetura: src/engenharia/arquitetura/arquitetura.md
      - Ajuda: 
        - src/engenharia/ajuda/index.md
        - src/engenharia/ajuda/erro_no_deploy.md
    - Glossário:
      - src\glossario\Glossario.md
    - Repasse:
      - src/repasse/repasse.md
    - Como documentar os projetos ?:
      - src/padrao/getting_started.md
      - src/padrao/arquitetura.md
      - src/padrao/desenvolvimento.md
      - src/padrao/novo_repositorio.md
